### ISSUE TITLE
转换AZW3没有封面

### ISSUE THREAD

**Issue by StrollStars** [dougmassay/kindleunpack-calibre-plugin#2]
如题，通过菜单KF8 to ePub功能，得到的ePub文件没有封面，不知从哪个版本开始的，到目前的最新版本都有这个问题。

**Comment by dougmassay** [comment]
I'm sorry, but github hasn't even provided something for me to try and translate, here. All I see are squares (like where characters are missing).

**Comment by mannahusum** [comment]
I can’t read it either, but I was able to recognize the text was written  in Kanji (Chinese) letters.

This is what google translated it to:

Such as the title, through the menu KF8 to ePub function, the ePub file is not a cover, I do not know from which version of the beginning, to the current version of the latest have this problem.

Hope that I could help.

On 5. März 2017 18:15:30 MEZ, Doug Massay <notifications@github.com> wrote:
>I'm sorry, but github hasn't even provided something for me to try and
>translate, here. All I see are squares (like where characters are
>missing). 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dougmassay/kindleunpack-calibre-plugin/issues/2#issuecomment-284244361

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by dougmassay** [comment]
Thanks @mannahusum. My fonts must be deficient in my browser. I had no characters to even try to guess—only squares.

Sounds like they're not getting a cover page when they unpack an EPUB from an AZW3. If so, that's likely an issue with the underlying KindleUnpack engine and not the plugin built around it.

I DO know that I quite often get a cover page (but not always) from my AZW3s with this plugin. But sometimes the Kindlebook simply has no cover image image defined. KindleUnpack extracts info like that from various indexes, and depending on what source was provided to build the Kindlebook, that info simply may not be present.

However, if you feel KindleUnpack really IS failing to extract/create a cover-page when it should be, I would create an issue for the [KindleUnpack](https://github.com/kevinhendricks/KindleUnpack) software and provide a link to a drm-free AZW3 that exhibits the behavior.

**Comment by StrollStars** [comment]
Thanks @mannahusum , that's right.
@dougmassay Please create an issue, thank you.

**Comment by 2ji3150** [comment]
I have this issue too
when covert azw3 to epub, there is no cover page.
