### ISSUE TITLE
Azw3 to epub no cover

### ISSUE THREAD

**Issue by 2ji3150** [dougmassay/kindleunpack-calibre-plugin#3]
This is a great plugin! But After converting there is no cover.
Please fix it.

**Comment by 2ji3150** [comment]
ok seems it does contains cover but the format is a little strange seems some reader can not see the cover like microsoft edge. A browser can read epub

**Comment by dougmassay** [comment]
If the kindlebook is an older style mobi, there will be no cover page. Even KF8s might not have cover-pages properly. Sigil makes it simple to create a cover page from an existing image.

This plugin is not intended to be turn-key solution for converting kindlebooks to epubs. It does not even guarantee the epub will validate. Most--if not all--kindlebooks will need work once opened in Sigil.

**Comment by 2ji3150** [comment]
Ok I see. But now I found that my book have 223pages cover is part 0223 which should be part 0000. 
I don't know which is it normal

**Comment by 2ji3150** [comment]
I mean the order is a little strange. The number of the cover is the last .  But some reader can recognize  that the last page is the cover page.
